[env:esp32dev]
platform = espressif32 @ 6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP32-audioI2S
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Iinclude
    -DMINI_AZAN_AUDIO_AUX_DAC=1
