; Run from this directory: pio run -t upload -t monitor

[env:xpt2046_touch_test]
platform = espressif32 @ 6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter

build_flags =
    -I../../include
    -DMINI_AZAN_TOUCH_STANDALONE=1
